### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by ayozebarrera** [WinterCore/react-text-transition#6]
Hi, nice component =)

You are still using componentWillReceiveProps and React is printing the following warning:

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Thank you!

**Comment by WinterCore** [comment]
Hi.
You're right, it's because I haven't updated this component since `componentWillReceiveProps` got deprecated in favor of `componentDidUpdate`.
I'll start working on updating it soon.
Thanks for reporting this.

**Comment by ayozebarrera** [comment]
Great! Thank you 💪🏼

**Comment by WinterCore** [comment]
@ayozebarrera The component has been completely rewritten. Check version 1.0.2
It now uses `react-spring` instead of `react-motion`
Breaking changes (refer to the docs for more info)
The `order` prop has been replaced with `direction`
The `config` prop has been renamed to `springConfig`
The `overflow` prop has been inverted and renamed to `noOverflow`
Feel free to ask questions if you have any.
Thanks again.
